<?php

namespace AC\core\modules\stocks\models;

use AC\core\system\model\BaseModel;

class StocksGroupsModel extends BaseModel
{
  protected $tableName = 'reservations_stocks_groups';

  public function rules()
  {
    return [
      ['title', 'required'],
      [['title', 'description'], 'string'],
      ['active', 'bool'],
    ]; // TODO: Change the autogenerated stub
  }
}