<?php

namespace AC\core\modules\membershipFees\engines;

use AC\core\system\engine\BaseEngine;

class MembershipFeesGroupsEngine extends BaseEngine
{
  public function tableName()
  {
    return 'membership_fees_groups'; // TODO: Change the autogenerated stub
  }
}