<?php

namespace AC\core\modules\membershipFees\models;

use AC\core\modules\membershipFees\engines\MembershipFeesClientDataEngine;
use AC\core\modules\membershipFees\tables\MembershipFeesClientDataTable;

class MembershipFeesClientDataModel extends MembershipFeesClientDataTable
{
  protected $baseEngine             = 'MembershipFeesClientDataEngine';
  /**
   * @var MembershipFeesClientDataEngine
   */
  protected $engine;


  public function rules()
  {
    return [
//      [['membership_fees_group', 'entry_date'], 'integer'],
      ['auto_transition_group', 'bool'],
    ];

  }

  public function attributes($reflection = false): array
  {
    return parent::attributes(true); // TODO: Change the autogenerated stub
  }
}