CREATE TABLE `{DB_DATABASE_NAME}`.`{DB_TABLE_PREFIX}clients`
(
  `client_id`            int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mode`                 enum('1','2') NOT NULL DEFAULT '1',
  `system_mode`          enum('1','0') NOT NULL DEFAULT '0' COMMENT '0-client, 1-admin',
  `super`                enum('0','1') NOT NULL DEFAULT '0' COMMENT '1-unlimited booking of outdoor courts',
  `area_type`            enum('0','1','2','3') NOT NULL DEFAULT '0',
  `club_state`           int(3) DEFAULT 1,
  `encash`               set('0','1','2') NOT NULL DEFAULT '0',
  `active`               enum('0','1') DEFAULT NULL,
  `nds`                  int(11) DEFAULT NULL,
  `discount`             int(11) DEFAULT NULL,
  `login`                varchar(50)           DEFAULT NULL,
  `password_md5`         varchar(100)          DEFAULT NULL,
  `number`               varchar(32)           DEFAULT NULL,
  `name`                 varchar(255) NOT NULL DEFAULT '',
  `surname`              varchar(255) NOT NULL DEFAULT '',
  `birthday`             date                  DEFAULT NULL,
  `phone`                varchar(255) NOT NULL DEFAULT '',
  `phone_mobile`         varchar(255) NOT NULL DEFAULT '',
  `fax`                  varchar(255) NOT NULL DEFAULT '',
  `city`                 varchar(255) NOT NULL DEFAULT '',
  `post_code`            varchar(255) NOT NULL DEFAULT '',
  `address`              mediumtext   NOT NULL,
  `email`                varchar(50)  NOT NULL DEFAULT '',
  `start_order_period`   date                  DEFAULT NULL,
  `order_period`         int(11) NOT NULL DEFAULT 0,
  `reservations_removed` int(10) unsigned NOT NULL DEFAULT 0,
  `registered`           datetime     NOT NULL DEFAULT '0000-00-00 00:00:00',
  `account_owner`        varchar(255)          DEFAULT NULL,
  `account_number`       varchar(255)          DEFAULT NULL,
  `bank_index`           varchar(255)          DEFAULT NULL,
  `bank_name`            varchar(255)          DEFAULT NULL,
  `codecard`             varchar(255)          DEFAULT NULL,
  `limit_day`            int(11) NOT NULL DEFAULT 0,
  `prepayment_sum`       double(10,2) DEFAULT 0.00,
  `stock_id`             text                  DEFAULT NULL,
  `sprice_id`            text                  DEFAULT NULL,
  `sepa_type`            enum('0','1') NOT NULL DEFAULT '0',
  `sepa_standart`        enum('0','1') NOT NULL DEFAULT '0',
  `bank_iban`            varchar(50)           DEFAULT NULL,
  `bank_bic`             varchar(20)           DEFAULT NULL,
  `bank_sepa_mandat`     date                  DEFAULT NULL,
  `bank_sepa_referenz`   varchar(250)          DEFAULT NULL,
  `unavailable_sports`   varchar(100)          DEFAULT NULL,
  `abo_delete`           tinyint(4) NOT NULL DEFAULT 0,
  `refund_for_ticket`    tinyint(4) NOT NULL DEFAULT 0,
  `refund_for_paypal`    tinyint(4) NOT NULL DEFAULT 0,
  `student`              enum('1','0') NOT NULL DEFAULT '0',
  `student_number`       varchar(255)          DEFAULT NULL,
  `firm`                 varchar(255)          DEFAULT NULL,
  `preferences`          longtext              DEFAULT NULL,
  PRIMARY KEY (`client_id`),
  KEY                    `user_id` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

