<?php

namespace AC\core\modules\tickets\controllers\admin;

use AC\app\locators\Service;

class TicketsFitnessController extends TicketsController
{

  public function __construct($action = false, $runController = true, $segments = [])
  {
    parent::__construct($action, $runController, $segments);
    Service::engines()->areas->setGroupType('fitness');
  }

  //  public function show()
//  {
//    Dbg($this);
//    return parent::show(); // TODO: Change the autogenerated stub
//  }

}